language: node_js
node_js:
  - "node"
script:
  - node build.js
deploy:
  - provider: pages
    local-dir: build
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    verbose: true
    on:
      branch: master
